server:
  port: 8001
spring:
  profiles:
    active: dev
good:
  saveimg: "D:\\project\\spring\\trading-platform\\img"
#    include:
luck-permission:
  packages: com.liuscraft.tradingplatform.controller
  refresh-permission: false
  verify-interceptors: com.liuscraft.tradingplatform.config.LuckVerifyImpl
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
  mapper-locations: classpath:/mapper/*.xml
mybatis:
  mapper-locations: classpath:/mapper/*.xml